### ISSUE TITLE
[Discussion]  Decide a tech stack

### ISSUE THREAD

**Issue by MadhavBahl** [TheLeanProgrammer/react#1]
Given that it's a static page - Plain HTML/CSS with Bootstrap or Materialize would work
But, React might help create some re-usable components for future (although that can be done trough plain HTML/CSS too)

@parindapranami - I'd leave decision to you

**Comment by parindapranami** [comment]
> Would you be using any CSS framework? Bootstrap/Materialize?

Yes, Bootstrap mostly.
