### ISSUE TITLE
Todos (26th Nov)

### ISSUE THREAD

**Issue by MadhavBahl** [TheLeanProgrammer/react#5]
- Fonts: Use CDN - https://fonts.google.com/specimen/Mulish?query=muli
- max width - 100vw (or 100%) and overflow x hidden
- Logo not there at top left
- Styles (remaining)
- [Section 1] - photo less width, and text vertically center
- Make images of less width (or responsive) (or max-width: 70%) so that they don't overflow in small screen

**Comment by parindapranami** [comment]
- [ ] Fonts: Use CDN - https://fonts.google.com/specimen/Mulish?query=muli 
- [ ] Logo not there at top left
- [ ] Styles (remaining)
